[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
headless = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
favicon = "favicon.png"

